// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdgeiuOvNew33yTQmxCg8RKu3ufyTv9Tk',
    appId: '1:29874856864:web:92f16b9e2ff67f1b3e7ac5',
    messagingSenderId: '29874856864',
    projectId: 'authenticationapp-e26c8',
    authDomain: 'authenticationapp-e26c8.firebaseapp.com',
    storageBucket: 'authenticationapp-e26c8.appspot.com',
    measurementId: 'G-W61QB90C8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgYT-YOMQN_O1pEs4Y30U-t9UehwyNvUI',
    appId: '1:29874856864:android:7362b3566b7d691c3e7ac5',
    messagingSenderId: '29874856864',
    projectId: 'authenticationapp-e26c8',
    storageBucket: 'authenticationapp-e26c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJXr7GrjjflrWCAbfhvYk0vL3N648xIs4',
    appId: '1:29874856864:ios:90c19211b747a72d3e7ac5',
    messagingSenderId: '29874856864',
    projectId: 'authenticationapp-e26c8',
    storageBucket: 'authenticationapp-e26c8.appspot.com',
    iosBundleId: 'com.example.groapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJXr7GrjjflrWCAbfhvYk0vL3N648xIs4',
    appId: '1:29874856864:ios:90c19211b747a72d3e7ac5',
    messagingSenderId: '29874856864',
    projectId: 'authenticationapp-e26c8',
    storageBucket: 'authenticationapp-e26c8.appspot.com',
    iosBundleId: 'com.example.groapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdgeiuOvNew33yTQmxCg8RKu3ufyTv9Tk',
    appId: '1:29874856864:web:b1ca217ff2fbe8453e7ac5',
    messagingSenderId: '29874856864',
    projectId: 'authenticationapp-e26c8',
    authDomain: 'authenticationapp-e26c8.firebaseapp.com',
    storageBucket: 'authenticationapp-e26c8.appspot.com',
    measurementId: 'G-N02P3QZW28',
  );
}
